plugins:
  - jekyll-relative-links
  - jekyll-rushed-analytics
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-tactile

jekyll_analytics:
  GoogleAnalytics4: # Add, if you want to track with Google Analytics 4
    measurement_id: G-22W86KJ0MT #
